### ISSUE TITLE
Quits

### ISSUE THREAD

**Issue by tbird301** [albertus82/earthquake-bulletin#13]
My Os is 10.14.6  When I launch Eartquake Bulletin it bounces in the dock & quits.  I'll send a crash report, if you could tell me were it would be located.

**Comment by albertus82** [comment]
Please check if there is a log file in in `/Users/<USERNAME>/Library/Earthquake Bulletin/log`. You can attach it here if you want. If there's no log in that folder or the folder does not exist, please open a terminal window and launch `java -version` to check if you have a suitable JRE installed. I just tried the application on macOS 11 with JRE 11. Thanks.

**Comment by tbird301** [comment]
Here's the info:
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

I also checked the Java Control Panel.  It says"Your system has the recommended version of Java.  Java 8 Update 311".  Hope this helps.

**Comment by tbird301** [comment]
I forgot to mention there was no folder in my home library.

**Comment by albertus82** [comment]
It seems the application is not starting at all.

Please:

1. make sure you downloaded the right package for your architecture (probably x86_64 based on you OS version);
2. open a terminal window in the folder containing the app;
3. execute `java -XstartOnFirstThread -jar Earthquake\ Bulletin.app/Contents/Resources/Java/EarthquakeBulletin.jar`

The application should start or print an error.

**Comment by tbird301** [comment]
I originally down loaded the app from MacUpdate.  Here’s what it showed: earthquake-bulletin-2.3.1-cocoa-macosx-aarch64-app.tar. Today, I went to your website & this is what I did.

1.  I picked  this to try & download it.
     earthquake-bulletin-2.3.1-cocoa-macosx-x86_64-app.tar.gz
99c02a91d4953f85368a71d8830d47b580a87724d9c16e3806056beeecc9af44 <https://www.virustotal.com/it/file/99c02a91d4953f85368a71d8830d47b580a87724d9c16e3806056beeecc9af44/analysis/>

2. I clicked on the blue portion since it showed x86_64, then this came up.
   
What did I do wrong?

**Comment by tbird301** [comment]
Update

I didn’t scroll down far enough.  I just downloaded, earthquake-bulletin-2.3.1-cocoa-macosx-x86_64-app.tar  I laughed the app, it quit as before.  I now I’m going to try the terminal again.  I’ll let you know what happens.

**Comment by tbird301** [comment]
I moved EarthQuake Bulletin to the Utilities folder because the Terminal app is in that folder.  This is what happened:

Last login: Tue Dec 21 12:52:10 on ttys000
Toms-Mac-Pro:~ tomfleck$ execute java -XstartOnFirstThread -jar Earthquake\ Bulletin.app/Contents/Resources/Java/EarthquakeBulletin.jar
-bash: execute: command not found
Toms-Mac-Pro:~ tomfleck$

**Comment by albertus82** [comment]
Please launch the command omitting "execute"; the command is only:

` java -XstartOnFirstThread -jar Earthquake\ Bulletin.app/Contents/Resources/Java/EarthquakeBulletin.jar`

**Comment by tbird301** [comment]
Sorry,  I’m a novice using the terminal.  Here’s the new results:

Last login: Tue Dec 21 13:06:48 on ttys000
Toms-Mac-Pro:~ tomfleck$ java -XstartOnFirstThread -jar Earthquake\ Bulletin.app/Contents/Resources/Java/EarthquakeBulletin.jar
Error: Unable to access jarfile Earthquake Bulletin.app/Contents/Resources/Java/EarthquakeBulletin.jar
Toms-Mac-Pro:~ tomfleck$

**Comment by albertus82** [comment]
If you launch

`ls -la`

what you see?

**Comment by tbird301** [comment]
Report:

Last login: Tue Dec 21 13:08:21 on ttys000
Toms-Mac-Pro:~ tomfleck$ ls -la
total 124664
drwxr-xr-x@ 177 tomfleck  staff      5664 Dec 21 09:51 .
-rw-r--r--    1 tomfleck  staff       266 Oct 28 19:05 .(null).padl
drwxr-xr-x    6 root      admin       192 Sep 16 20:00 ..
-rw-r--r--    1 tomfleck  staff       261 Dec  1  2015 .308.padl
-rw-r--r--    1 tomfleck  staff       261 Jun  1  2016 .3769.padl
-rw-r--r--    1 tomfleck  staff       261 Jul 13 19:46 .489429.padl
-rw-r--r--    1 tomfleck  staff       261 Dec  1  2015 .490236.padl
-rw-r--r--    1 tomfleck  staff       261 May 21  2017 .490926.padl
-rw-r--r--    1 tomfleck  staff       261 May 31  2016 .491062.padl
-rw-r--r--    1 tomfleck  staff       266 Oct  4  2020 .496621.padl
-rw-r--r--    1 tomfleck  staff       261 Jul 17 14:54 .497873.padl
-rw-r--r--    1 tomfleck  staff       261 Jun 17  2019 .497944.padl
-rw-r--r--    1 tomfleck  staff       261 Jun 17  2019 .498333.padl
-rw-r--r--    1 tomfleck  staff       261 Jan 17  2016 .499167.padl
-rw-r--r--    1 tomfleck  staff       261 Dec  1  2015 .499782.padl
-rw-r--r--    1 tomfleck  staff       261 Dec  1  2015 .501548.padl
-rw-r--r--    1 tomfleck  staff       261 Jul 19  2019 .509579.padl
-rw-r--r--    1 tomfleck  staff       261 Jun 13  2017 .513792.padl
-rw-------    1 tomfleck  staff         7 Jul  6 13:29 .CFUserTextEncoding
drwx------    2 tomfleck  staff        64 Aug 31 12:53 .DDPreview
-rw-r--r--@   1 tomfleck  staff     43012 Dec 21 10:09 .DS_Store
drwxr-xr-x    3 tomfleck  staff        96 May  9  2021 .ET_TVC
-rw-r--r--    1 tomfleck  staff       223 Oct  7  2014 .ICUTF8D
-rw-r--r--    1 tomfleck  staff         0 Jan 19  2007 .KSMB
drwxr-xr-x    4 tomfleck  staff       128 Mar  9  2011 .MacOSX
-rwxrwxrwx@   1 tomfleck  staff        38 Aug  2  2011 .PermissionsScript
drwxr-xr-x    7 tomfleck  staff       224 Dec 24  2010 .PersonalBrain
-rw-r--r--    1 tomfleck  staff         0 Oct 27  2014 .Rapp.history
-rwxrwxrwx@   1 tomfleck  staff        25 Aug  2  2011 .RebootScript
-rw-r--r--    1 tomfleck  staff         0 Oct 27  2014 .Rhistory
drwxrwxrwt@   3 tomfleck  staff        96 Jul 30  2006 .TemporaryItems
drwx------    5 tomfleck  staff       160 Dec 21 13:16 .Trash
-rw-------    1 tomfleck  staff         0 Sep 13 20:03 .Xauthority
drwxr-xr-x    5 tomfleck  staff       160 Dec 14  2016 .android
-rw-r--r--    1 tomfleck  staff        28 Oct  9  2014 .ano
drwxr-xr-x    2 tomfleck  staff        64 Oct 15  2014 .artofillusion
-rw-r--r--    1 tomfleck  staff    301195 Nov  2 09:06 .babel.json
-rw-------    1 tomfleck  staff       561 Dec 21 13:10 .bash_history
-rw-r--r--    1 tomfleck  staff      4373 Dec 17 19:45 .bash_profile
-rw-r--r--    1 tomfleck  staff      4203 Oct 27 13:00 .bash_profile.pysave
drwx------   22 tomfleck  staff       704 Dec 21 13:20 .bash_sessions
drwxr-xr-x    3 tomfleck  staff        96 Aug 11 14:28 .biblioteq
drwx------    3 tomfleck  staff        96 Apr 11  2007 .bittorrent
-rw-r--r--    1 tomfleck  staff       192 Nov 28  2017 .c5f6f698.dwk
drwxr-xr-x    4 tomfleck  staff       128 Dec 16 08:52 .cache
drwxr-xr-x   11 tomfleck  staff       352 Oct 25 12:39 .config
drwxr-xr-x    5 tomfleck  staff       160 Feb  3  2015 .dangerdeep
drwx------   16 tomfleck  staff       512 Dec  5 12:31 .dropbox
-rw-r--r--    1 tomfleck  staff      1157 Feb  3  2015 .enigmarc.xml
drwxr-xr-x    4 tomfleck  staff       128 Feb  1  2015 .etracer
drwxr-xr-x    3 tomfleck  staff        96 Dec 25  2008 .fgfs
drwxr-xr-x    3 tomfleck  staff        96 Feb  3  2015 .fillets-ng
-rwxr-xr-x    1 tomfleck  staff        61 Nov 24  2014 .flexlmrc
drwxr-xr-x    3 tomfleck  staff        96 May 21  2021 .freeplane
drwxr-x---    4 tomfleck  staff       128 Feb  3  2015 .frogatto
drwx------    2 tomfleck  staff        64 Sep 28  2014 .gnome2
drwx------@   3 tomfleck  staff        96 Jun 13  2017 .gnupg
drwxr-xr-x    3 tomfleck  staff        96 Apr 24  2009 .inkscape
drwxr-xr-x    9 tomfleck  staff       288 Sep 28  2014 .inkscape-etc
drwxr-xr-x    4 tomfleck  staff       128 Feb 22  2007 .jdiskreport
drwxr-xr-x    6 tomfleck  staff       192 Jan 19  2007 .jmvision1_25
drwxr-xr-x    6 tomfleck  staff       192 Sep 26  2009 .jmvision1_27
drwx------    4 tomfleck  staff       128 Oct 10  2014 .local
-rw-r--r--    1 tomfleck  staff      1471 Jun  7  2016 .mailcap
-rw-r--r--    1 tomfleck  staff       764 Jun  7  2016 .mime.types
drwxr-xr-x    3 tomfleck  staff        96 Sep 27  2014 .mplayer
drwxr-xr-x    2 tomfleck  staff        64 Jan 12  2012 .narya
drwxrwxrwx   12 tomfleck  staff       384 Jul 27 09:25 .nchsoftware
drwx------    6 tomfleck  staff       192 Feb  2  2015 .neverball
drwxr-xr-x    3 tomfleck  staff        96 Jun  2  2007 .nexuiz
drwxr-xr-x   63 tomfleck  staff      2016 May 21  2017 .npm
drwx------   14 tomfleck  staff       448 Oct 28 16:07 .nx
drwxr-xr-x    8 tomfleck  staff       256 Dec 21 09:45 .oracle_jre_usage
drwxr-xr-x    5 tomfleck  staff       160 Feb  2  2015 .outerspace
drwxr-xr-x    3 tomfleck  staff        96 Sep 30  2014 .plexht
drwxr-xr-x    9 tomfleck  staff       288 Feb  2  2015 .privgold100
drwx------    6 tomfleck  staff       192 Feb  2  2015 .pysol
-rw-r--r--    1 tomfleck  staff       284 Feb 12  2017 .qp_info
drwx------    3 tomfleck  staff        96 Oct 30  2018 .qt
-rw-------    1 tomfleck  staff      1024 Jun 28 14:50 .rnd
drwxr-xr-x   12 tomfleck  staff       384 Oct 27  2014 .rstudio-desktop
drwxr-xr-x    6 tomfleck  staff       192 Jan  4  2015 .rvwmx
drwxr-xr-x    5 tomfleck  staff       160 Dec 24  2008 .sabnzbd
drwxrwxrwx   23 tomfleck  staff       736 Dec 23  2015 .spotflux
lrwxr-xr-x@   1 tomfleck  staff        50 Feb 11  2015 .spumux -> /Library/Application Support/Media Converter/Fonts
drwxr-xr-x    2 tomfleck  staff        64 Oct 16  2014 .ssh
drwxr-xr-x    6 tomfleck  staff       192 Oct 27  2014 .subversion
drwxr-xr-x    3 tomfleck  staff        96 Aug 20  2012 .swt
drwxr-xr-x    4 tomfleck  staff       128 Oct 15  2014 .thumbnails
drwxr-xr-x    3 tomfleck  staff        96 Oct  6  2014 .tuxguitar-1.2
drwxr-xr-x    9 tomfleck  staff       288 Sep 30  2014 .ultramixer
drwxr-xr-x    3 tomfleck  staff        96 Sep 30  2014 .vim
-rw-------    1 tomfleck  staff      4611 Sep 30  2014 .viminfo
drwxr-xr-x    3 tomfleck  staff        96 Nov 20  2010 .wally
drwxr-xr-x    4 tomfleck  staff       128 Feb  2  2015 .wapi
drwxr-xr-x    3 tomfleck  staff        96 Jun 26  2015 .wireshark
drwxr-xr-x    7 tomfleck  staff       224 Jun 26  2015 .wireshark-etc
drwxr-xr-x    3 tomfleck  staff        96 Dec 26  2006 .xine
-rw-r--r--    1 tomfleck  staff       587 Oct  3  2008 .xinitrc.old
-rw-r--r--    1 tomfleck  staff         0 Mar  1  2007 .xprocess1.applist
-rw-r--r--    1 tomfleck  staff       567 Jan  8  2017 .zazurc.json
-rw-r--r--    1 tomfleck  staff       578 May  4  2009 AT.postflight.2197
-rw-r--r--    1 tomfleck  staff       578 Nov  2  2014 AT.postflight.5870
drwxr-xr-x   11 tomfleck  staff       352 Mar  5  2017 Analog Projects 3
drwx------   35 tomfleck  staff      1120 Nov 30 14:11 Applications
-rw-r--r--    1 tomfleck  staff    161039 Nov 16  2020 AquaGraphite.style
drwxr-xr-x    4 tomfleck  staff       128 Nov  5  2014 AutoStacks
-rw-r--r--    1 tomfleck  staff      5673 Jul 12 17:35 Banded Swirl.jpg
-rw-r--r--    1 tomfleck  staff      5317 Jul 12 17:35 Bands.jpg
drwxr-xr-x   11 tomfleck  staff       352 Oct 18  2016 BlackWhite Projects 4
drwxr-xr-x   11 tomfleck  staff       352 Feb 26  2018 BlackWhite Projects 5
-rw-r--r--@   1 tomfleck  staff      3889 Jul 12 17:35 Bokeh.jpg
-rw-r--r--    1 tomfleck  staff      3704 Jul 12 17:35 Box Blur.jpg
-rw-r--r--    1 tomfleck  staff      4536 Sep  1 12:16 Brush Stroke Texture 2.jpg
drwxr-xr-x    7 tomfleck  staff       224 Nov 28  2019 Calibre Library
drwxr-xr-x   11 tomfleck  staff       352 Jun  7  2016 Color Projects 4
-rw-r--r--    1 tomfleck  staff      5475 Jul 12 17:35 Crumple.jpg
drwxr-xr-x   12 tomfleck  staff       384 Sep  3  2017 DeNoise Projects 2 Pro
drwxr-xr-x   10 tomfleck  staff       320 Jun  1  2016 DeNoise Projects Pro
drwx------@   9 tomfleck  staff       288 Dec 21 12:45 Desktop
-rw-r--r--@   1 tomfleck  staff      2155 Jul 25  2007 DesktopundefinedmyScreen0.pdf
drwx------@ 175 tomfleck  staff      5600 Nov 15 08:35 Documents
drwx------@   7 tomfleck  staff       224 Dec 21 13:17 Downloads
drwx------@  15 tomfleck  staff       480 Dec  5 12:31 Dropbox
-rw-r--r--    1 tomfleck  staff         1 Jul 21  2007 Duplicate_Annihilator_debug.log
-rw-r--r--    1 tomfleck  staff     27793 Jul 21  2007 Duplicate_Annihilator_progress.log
drwxr-xr-x   13 tomfleck  staff       416 Aug 12 14:28 Emotion Projects 1 Pro
drwxr-xr-x   15 tomfleck  staff       480 Dec 25  2016 ExaChess Games
-rw-r--r--@   1 tomfleck  staff       679 Jul 12 17:35 Fill Color.jpg
-rw-r--r--    1 tomfleck  staff    412410 Jul 12 17:35 Filter Submission.jpg
-rw-r--r--    1 tomfleck  staff      3525 Nov 16  2020 FilterMacro.txt
drwxr-xr-x   10 tomfleck  staff       320 Jan  3  2017 Focus Projects 3 Pro
drwxr-xr-x    5 tomfleck  staff       160 Dec 25  2016 FrostWire
-rw-r--r--    1 tomfleck  staff      1940 Jul 12 17:35 Gaussian Blur 2.jpg
drwxr-xr-x   15 tomfleck  staff       480 Jan 19  2019 HDR Projects 2018 Pro
drwxr-xr-x   13 tomfleck  staff       416 Oct 21  2018 HDR Projects 4 Pro
drwxr-xr-x   13 tomfleck  staff       416 Oct 21  2018 HDR Projects 5 Pro
-rw-r--r--    1 tomfleck  staff  62499546 Nov 16  2020 Imagelys MS.data
drwxr-xr-x    3 tomfleck  staff        96 Mar 13  2018 Incomplete
drwxr-xr-x    4 tomfleck  staff       128 Nov 22  2016 InstallShield
drwx------+ 166 tomfleck  staff      5312 Dec 21 12:46 Library
-rw-r--r--    1 tomfleck  staff      3678 Jul 12 17:35 Make Seamless.jpg
drwx------@  30 tomfleck  staff       960 Dec  1 13:11 Movies
drwx------@  19 tomfleck  staff       608 Jul 10 08:25 Music
drwxr-xr-x   12 tomfleck  staff       384 Mar  8  2019 Nature Projects 1
drwxrwxrwx    7 tomfleck  staff       224 Dec  1 12:45 Pagico Data.pgco
-rw-r--r--    1 tomfleck  staff      5328 Jul 12 17:35 Paper Sketch.jpg
-rw-r--r--    1 tomfleck  staff      4973 Jul 12 17:35 Pencil Stroke.jpg
drwx------@  89 tomfleck  staff      2848 Nov 14 14:10 Pictures
drwxr-xr-x   16 tomfleck  staff       512 Aug 13 12:46 Projects Series
drwxr-xr-x+   7 tomfleck  staff       224 Oct 29  2014 Public
-rw-r--r--@   1 tomfleck  staff      4007 Jul 12 17:35 Radial Blur.jpg
-rw-r--r--    1 tomfleck  staff      4086 Jul 12 17:35 RemixColors.jpg
-rw-r--r--    1 tomfleck  staff      4944 Sep  1 12:16 Replace Colors.jpg
-rw-r--r--    1 tomfleck  staff      5011 Jul 12 17:35 Ripple 2.jpg
drwxr-xr-x    4 tomfleck  staff       128 Nov 22  2016 Shared
drwxr-xr-x   10 tomfleck  staff       320 Aug 13 12:47 Sharpen Projects Pro
drwxr-xr-x    9 tomfleck  staff       288 Jun 11  2016 Silver Projects Pro
drwxr-xr-x+   6 tomfleck  staff       192 Nov 22  2016 Sites
drwxr-xr-x    4 tomfleck  staff       128 Nov 22  2016 SmithMicroDownloadManager
-rw-------    1 tomfleck  staff         5 Dec  2  2015 SmithMicroDownloadManager-tomfleck
drwxr-xr-x@   6 tomfleck  staff       192 Nov 22  2016 Tag Folders
-rw-r--r--    1 tomfleck  staff      4343 Apr 23  2007 Tom's Aqua 1.FishList
-rw-r--r--    1 tomfleck  staff      5567 Jul 12 17:35 Toon.jpg
drwxrwxrwx@   3 tomfleck  staff        96 Apr 26  2009 Uninstall Neverball.mpkg
drwxr-xr-x    8 tomfleck  staff       256 Nov 15  2018 UserContent
-rw-r--r--@   1 tomfleck  staff      4946 Jul 12 17:35 Wave.jpg
-rw-r--r--    1 tomfleck  staff      4873 Jul 12 17:35 Wiggle.jpg
drwxr-xr-x    3 tomfleck  staff        96 Mar 23  2012 XRG Themes
drwxr-xr-x    8 tomfleck  staff       256 Dec 25  2016 cfx
-rw-r--r--    1 tomfleck  staff     51062 Dec 30  2014 ems.cfg
-rw-r--r--    1 tomfleck  staff      5174 Nov 16  2020 grad.bmp
drwxr-xr-x    7 tomfleck  staff       224 Nov 22  2016 iMacros
drwxr-xr-x@   3 tomfleck  staff        96 Feb  7  2018 iec
drwxr-xr-x    9 tomfleck  staff       288 Jul 26  2008 lib
-rw-r--r--    1 tomfleck  staff      2184 Nov 16  2020 presetsfilter.cfg
-rw-r--r--@   1 tomfleck  staff        59 Oct  6 19:43 times.csv
Toms-Mac-Pro:~ tomfleck$

**Comment by albertus82** [comment]
You are in your home folder (`~`) and `Earthquake Bulletin.app` is not in that folder.

To make things simpler: 

1. download https://github.com/albertus82/earthquake-bulletin/releases/download/v2.3.1/earthquake-bulletin-2.3.1-cocoa-macosx-x86_64-app.tar.gz to your Desktop
2. double-click the downloaded file so it unpacks itself; the Earthquake Bulletin icon should appear on the Desktop.
3. open a terminal
4. `cd Desktop`
5. `java -XstartOnFirstThread -jar Earthquake\ Bulletin.app/Contents/Resources/Java/EarthquakeBulletin.jar`

**Comment by tbird301** [comment]
I want to thank you for your patience in this matter.  Here’s the report:

Last login: Tue Dec 21 13:46:16 on ttys000
Toms-Mac-Pro:~ tomfleck$ cd Desktop
Toms-Mac-Pro:Desktop tomfleck$ java -XstartOnFirstThread -jar Earthquake\ Bulletin.app/Contents/Resources/Java/EarthquakeBulletin.jar
2021-12-21 13:52:30.610 [main] ERROR it.albertus.eqbulletin.gui.EarthquakeBulletinGui - An unrecoverable error has occurred:
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cocoa-4944r26 in java.library.path
	no swt-cocoa in java.library.path
	no swt in java.library.path
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: dlopen(/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib, 1): no suitable image found.  Did find:
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: mach-o, but wrong architecture
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: mach-o, but wrong architecture
	Can't load library: /Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa.jnilib
	Can't load library: /Users/tomfleck/.swt/lib/macosx/x86_64/libswt.jnilib
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: dlopen(/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib, 1): no suitable image found.  Did find:
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: mach-o, but wrong architecture
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: mach-o, but wrong architecture

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:348)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:107)
	at it.albertus.eqbulletin.gui.EarthquakeBulletinGui.main(EarthquakeBulletinGui.java:106)
	at it.albertus.eqbulletin.EarthquakeBulletin.main(EarthquakeBulletin.java:11)
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cocoa-4944r26 in java.library.path
	no swt-cocoa in java.library.path
	no swt in java.library.path
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: dlopen(/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib, 1): no suitable image found.  Did find:
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: mach-o, but wrong architecture
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: mach-o, but wrong architecture
	Can't load library: /Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa.jnilib
	Can't load library: /Users/tomfleck/.swt/lib/macosx/x86_64/libswt.jnilib
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: dlopen(/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib, 1): no suitable image found.  Did find:
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: mach-o, but wrong architecture
	/Users/tomfleck/.swt/lib/macosx/x86_64/libswt-cocoa-4944r26.jnilib: mach-o, but wrong architecture

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:348)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:107)
	at it.albertus.eqbulletin.gui.EarthquakeBulletinGui.main(EarthquakeBulletinGui.java:106)
	at it.albertus.eqbulletin.EarthquakeBulletin.main(EarthquakeBulletin.java:11)
Toms-Mac-Pro:Desktop tomfleck$

**Comment by albertus82** [comment]
You're welcome. Probably I figured out why the application won't start on your machine: the reason is that you tried to start the wrong version before.

Please open a terminal window and execute the following command (copy & paste it if you can't type the `~` symbol):

`mv ~/.swt ~/.swt.old`

Then launch the application double clicking the icon on the Desktop and let me know if it works.

**Comment by tbird301** [comment]
Alberto,

Here’s what happened:  SUCCESS!


Is there tutorial available to show how to operate your Application?

Thanks again!
Tom

**Comment by tbird301** [comment]
I played with the app & got it working.]
